// Get country name from iso code. Return undefined if iso code is not valid
export const countryIsoToName = (isoCode: string): string => {
  const upperCaseIsoCode = isoCode.toUpperCase();
  return countries[upperCaseIsoCode];
};

export const countryNameToIso = (countryName: string): string => {
  return countriesNameIso[countryName];
};

const countries = {
  'UNKNOWN': 'Unknown',
  'AD': 'Andorra',
  'AE': 'United Arab Emirates',
  'AF': 'Afghanistan',
  'AG': 'Antigua and Barbuda',
  'AI': 'Anguilla',
  'AL': 'Albania',
  'AM': 'Armenia',
  'AO': 'Angola',
  'AQ': 'Antarctica',
  'AR': 'Argentina',
  'AS': 'American Samoa',
  'AT': 'Austria',
  'AU': 'Australia',
  'AW': 'Aruba',
  'AX': 'Aland Islands',
  'AZ': 'Azerbaijan',
  'BA': 'Bosnia and Herzegovina',
  'BB': 'Barbados',
  'BD': 'Bangladesh',
  'BE': 'Belgium',
  'BF': 'Burkina Faso',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BI': 'Burundi',
  'BJ': 'Benin',
  'BL': 'Saint Barthelemy',
  'BM': 'Bermuda',
  'BN': 'Brunei',
  'BO': 'Bolivia',
  'BQ': 'Bonaire',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BT': 'Bhutan',
  'BV': 'Bouvet Island',
  'BW': 'Botswana',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'CA': 'Canada',
  'CC': 'Cocos Islands',
  'CD': 'Democratic Republic of the Congo',
  'CF': 'Central African Republic',
  'CG': 'Republic of the Congo',
  'CH': 'Switzerland',
  'CI': 'Ivory Coast',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CV': 'Cabo Verde',
  'CW': 'Curacao',
  'CX': 'Christmas Island',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DK': 'Denmark',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'EH': 'Western Sahara',
  'ER': 'Eritrea',
  'ES': 'Spain',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FK': 'Falkland Islands',
  'FM': 'Micronesia',
  'FO': 'Faroe Islands',
  'FR': 'France',
  'GA': 'Gabon',
  'GB': 'United Kingdom',
  'GD': 'Grenada',
  'GE': 'Georgia',
  'GF': 'French Guiana',
  'GG': 'Guernsey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Greenland',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GP': 'Guadeloupe',
  'GQ': 'Equatorial Guinea',
  'GR': 'Greece',
  'GS': 'South Georgia and the South Sandwich Islands',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HM': 'Heard Island and McDonald Islands',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IM': 'Isle of Man',
  'IN': 'India',
  'IO': 'British Indian Ocean Territory',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JE': 'Jersey',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KH': 'Cambodia',
  'KI': 'Kiribati',
  'KM': 'Comoros',
  'KN': 'Saint Kitts and Nevis',
  'KP': 'North Korea',
  'KR': 'South Korea',
  'XK': 'Kosovo',
  'KW': 'Kuwait',
  'KY': 'Cayman Islands',
  'KZ': 'Kazakhstan',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LC': 'Saint Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'LY': 'Libya',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldova',
  'ME': 'Montenegro',
  'MF': 'Saint Martin',
  'MG': 'Madagascar',
  'MH': 'Marshall Islands',
  'MK': 'North Macedonia',
  'ML': 'Mali',
  'MM': 'Myanmar',
  'MN': 'Mongolia',
  'MO': 'Macao',
  'MP': 'Northern Mariana Islands',
  'MQ': 'Martinique',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MW': 'Malawi',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NC': 'New Caledonia',
  'NE': 'Niger',
  'NF': 'Norfolk Island',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NU': 'Niue',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'French Polynesia',
  'PG': 'Papua New Guinea',
  'PH': 'Philippines',
  'PK': 'Pakistan',
  'PL': 'Poland',
  'PM': 'Saint Pierre and Miquelon',
  'PN': 'Pitcairn',
  'PR': 'Puerto Rico',
  'PS': 'Palestinian Territory',
  'PT': 'Portugal',
  'PW': 'Palau',
  'PY': 'Paraguay',
  'QA': 'Qatar',
  'RE': 'Reunion',
  'RO': 'Romania',
  'RS': 'Serbia',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SA': 'Saudi Arabia',
  'SB': 'Solomon Islands',
  'SC': 'Seychelles',
  'SD': 'Sudan',
  'SS': 'South Sudan',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'SH': 'Saint Helena',
  'SI': 'Slovenia',
  'SJ': 'Svalbard and Jan Mayen',
  'SK': 'Slovakia',
  'SL': 'Sierra Leone',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Suriname',
  'ST': 'Sao Tome and Principe',
  'SV': 'El Salvador',
  'SX': 'Sint Maarten',
  'SY': 'Syria',
  'SZ': 'Eswatini',
  'TC': 'Turks and Caicos Islands',
  'TD': 'Chad',
  'TF': 'French Southern Territories',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TK': 'Tokelau',
  'TL': 'Timor Leste',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TR': 'Turkey',
  'TT': 'Trinidad and Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'UM': 'United States Minor Outlying Islands',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VA': 'Vatican',
  'VC': 'Saint Vincent and the Grenadines',
  'VE': 'Venezuela',
  'VG': 'British Virgin Islands',
  'VI': 'U.S. Virgin Islands',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis and Futuna',
  'WS': 'Samoa',
  'YE': 'Yemen',
  'YT': 'Mayotte',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'CS': 'Serbia and Montenegro',
  'AN': 'Netherlands Antilles',
};

const countriesNameIso = {
  'Unknown': 'Unknown',
  'Andorra': 'AD',
  'United Arab Emirates': 'AE',
  'Afghanistan': 'AF',
  'Antigua and Barbuda': 'AG',
  'Anguilla': 'AI',
  'Albania': 'AL',
  'Armenia': 'AM',
  'Angola': 'AO',
  'Antarctica': 'AQ',
  'Argentina': 'AR',
  'American Samoa': 'AS',
  'Austria': 'AT',
  'Australia': 'AU',
  'Aruba': 'AW',
  'Aland Islands': 'AX',
  'Azerbaijan': 'AZ',
  'Bosnia and Herzegovina': 'BA',
  'Barbados': 'BB',
  'Bangladesh': 'BD',
  'Belgium': 'BE',
  'Burkina Faso': 'BF',
  'Bulgaria': 'BG',
  'Bahrain': 'BH',
  'Burundi': 'BI',
  'Benin': 'BJ',
  'Saint Barthelemy': 'BL',
  'Bermuda': 'BM',
  'Brunei': 'BN',
  'Bolivia': 'BO',
  'Bonaire': 'BQ',
  'Brazil': 'BR',
  'Bahamas': 'BS',
  'Bhutan': 'BT',
  'Bouvet Island': 'BV',
  'Botswana': 'BW',
  'Belarus': 'BY',
  'Belize': 'BZ',
  'Canada': 'CA',
  'Cocos Islands': 'CC',
  'Democratic Republic of the Congo': 'CD',
  'Central African Republic': 'CF',
  'Republic of the Congo': 'CG',
  'Switzerland': 'CH',
  'Ivory Coast': 'CI',
  'Cook Islands': 'CK',
  'Chile': 'CL',
  'Cameroon': 'CM',
  'China': 'CN',
  'Colombia': 'CO',
  'Costa Rica': 'CR',
  'Cuba': 'CU',
  'Cabo Verde': 'CV',
  'Curacao': 'CW',
  'Christmas Island': 'CX',
  'Cyprus': 'CY',
  'Czechia': 'CZ',
  'Germany': 'DE',
  'Djibouti': 'DJ',
  'Denmark': 'DK',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Algeria': 'DZ',
  'Ecuador': 'EC',
  'Estonia': 'EE',
  'Egypt': 'EG',
  'Western Sahara': 'EH',
  'Eritrea': 'ER',
  'Spain': 'ES',
  'Ethiopia': 'ET',
  'Finland': 'FI',
  'Fiji': 'FJ',
  'Falkland Islands': 'FK',
  'Micronesia': 'FM',
  'Faroe Islands': 'FO',
  'France': 'FR',
  'Gabon': 'GA',
  'United Kingdom': 'GB',
  'Grenada': 'GD',
  'Georgia': 'GE',
  'French Guiana': 'GF',
  'Guernsey': 'GG',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greenland': 'GL',
  'Gambia': 'GM',
  'Guinea': 'GN',
  'Guadeloupe': 'GP',
  'Equatorial Guinea': 'GQ',
  'Greece': 'GR',
  'South Georgia and the South Sandwich Islands': 'GS',
  'Guatemala': 'GT',
  'Guam': 'GU',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Hong Kong': 'HK',
  'Heard Island and McDonald Islands': 'HM',
  'Honduras': 'HN',
  'Croatia': 'HR',
  'Haiti': 'HT',
  'Hungary': 'HU',
  'Indonesia': 'ID',
  'Ireland': 'IE',
  'Israel': 'IL',
  'Isle of Man': 'IM',
  'India': 'IN',
  'British Indian Ocean Territory': 'IO',
  'Iraq': 'IQ',
  'Iran': 'IR',
  'Iceland': 'IS',
  'Italy': 'IT',
  'Jersey': 'JE',
  'Jamaica': 'JM',
  'Jordan': 'JO',
  'Japan': 'JP',
  'Kenya': 'KE',
  'Kyrgyzstan': 'KG',
  'Cambodia': 'KH',
  'Kiribati': 'KI',
  'Comoros': 'KM',
  'Saint Kitts and Nevis': 'KN',
  'North Korea': 'KP',
  'South Korea': 'KR',
  'Kosovo': 'XK',
  'Kuwait': 'KW',
  'Cayman Islands': 'KY',
  'Kazakhstan': 'KZ',
  'Laos': 'LA',
  'Lebanon': 'LB',
  'Saint Lucia': 'LC',
  'Liechtenstein': 'LI',
  'Sri Lanka': 'LK',
  'Liberia': 'LR',
  'Lesotho': 'LS',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Latvia': 'LV',
  'Libya': 'LY',
  'Morocco': 'MA',
  'Monaco': 'MC',
  'Moldova': 'MD',
  'Montenegro': 'ME',
  'Saint Martin': 'MF',
  'Madagascar': 'MG',
  'Marshall Islands': 'MH',
  'North Macedonia': 'MK',
  'Mali': 'ML',
  'Myanmar': 'MM',
  'Mongolia': 'MN',
  'Macao': 'MO',
  'Northern Mariana Islands': 'MP',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Montserrat': 'MS',
  'Malta': 'MT',
  'Mauritius': 'MU',
  'Maldives': 'MV',
  'Malawi': 'MW',
  'Mexico': 'MX',
  'Malaysia': 'MY',
  'Mozambique': 'MZ',
  'Namibia': 'NA',
  'New Caledonia': 'NC',
  'Niger': 'NE',
  'Norfolk Island': 'NF',
  'Nigeria': 'NG',
  'Nicaragua': 'NI',
  'Netherlands': 'NL',
  'Norway': 'NO',
  'Nepal': 'NP',
  'Nauru': 'NR',
  'Niue': 'NU',
  'New Zealand': 'NZ',
  'Oman': 'OM',
  'Panama': 'PA',
  'Peru': 'PE',
  'French Polynesia': 'PF',
  'Papua New Guinea': 'PG',
  'Philippines': 'PH',
  'Pakistan': 'PK',
  'Poland': 'PL',
  'Saint Pierre and Miquelon': 'PM',
  'Pitcairn': 'PN',
  'Puerto Rico': 'PR',
  'Palestinian Territory': 'PS',
  'Portugal': 'PT',
  'Palau': 'PW',
  'Paraguay': 'PY',
  'Qatar': 'QA',
  'Reunion': 'RE',
  'Romania': 'RO',
  'Serbia': 'RS',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'Saudi Arabia': 'SA',
  'Solomon Islands': 'SB',
  'Seychelles': 'SC',
  'Sudan': 'SD',
  'South Sudan': 'SS',
  'Sweden': 'SE',
  'Singapore': 'SG',
  'Saint Helena': 'SH',
  'Slovenia': 'SI',
  'Svalbard and Jan Mayen': 'SJ',
  'Slovakia': 'SK',
  'Sierra Leone': 'SL',
  'San Marino': 'SM',
  'Senegal': 'SN',
  'Somalia': 'SO',
  'Suriname': 'SR',
  'Sao Tome and Principe': 'ST',
  'El Salvador': 'SV',
  'Sint Maarten': 'SX',
  'Syria': 'SY',
  'Eswatini': 'SZ',
  'Turks and Caicos Islands': 'TC',
  'Chad': 'TD',
  'French Southern Territories': 'TF',
  'Togo': 'TG',
  'Thailand': 'TH',
  'Tajikistan': 'TJ',
  'Tokelau': 'TK',
  'Timor Leste': 'TL',
  'Turkmenistan': 'TM',
  'Tunisia': 'TN',
  'Tonga': 'TO',
  'Turkey': 'TR',
  'Trinidad and Tobago': 'TT',
  'Tuvalu': 'TV',
  'Taiwan': 'TW',
  'Tanzania': 'TZ',
  'Ukraine': 'UA',
  'Uganda': 'UG',
  'United States Minor Outlying Islands': 'UM',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vatican': 'VA',
  'Saint Vincent and the Grenadines': 'VC',
  'Venezuela': 'VE',
  'British Virgin Islands': 'VG',
  'U.S. Virgin Islands': 'VI',
  'Vietnam': 'VN',
  'Vanuatu': 'VU',
  'Wallis and Futuna': 'WF',
  'Samoa': 'WS',
  'Yemen': 'YE',
  'Mayotte': 'YT',
  'South Africa': 'ZA',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Serbia and Montenegro': 'CS',
  'Netherlands Antilles': 'AN',
};
